apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rp-pods
  labels: 
    app: myapp
    env: dev
  namespace: devnamespace
  annotations:
    myecrimage: 503427799577.dkr.ecr.us-east-2.amazonaws.com/dev/myownimage:latest
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchExpressions:
      - key: web
        operator: In
        values:
          - yellowapp-pods
      - key: env
        operator: NotIn
        values: 
          - dev
      - key:  frontend
        operator: Exists
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      name: podlevellables
      labels:
        web: yellowllapp-pods
        env: prod
        frontend: web
    spec: 
      containers:
        - name: yellowimage
          image: hemanth65/hemanth-electricimage
          ports:
            - name: yellowapp-ports
              containerPort: 80
              protocol: TCP
          startupProbe: 
            httpGet:
              path: "/"
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            exec:
              command:
                - echo hi
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 300Mi
           



    