apiversion: apps/v1 
kind: Deployment  
metadata: 
  name: rp-pods
  lables: 
    app: myapp
    env: dev
  namespace: devnamespace
  annotations:
    myecrimage: 
spec:
  miniReadySeconds: 6
  replicas: 4
  selector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - yellowapp-pods
      - key: env
        operator: NotIn
        values: 
          - dev
      - key:  frontend
        operator: Exists
  stratergy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavilable: 1
  template: 
    metadata:
      name: podlevellables
      lables:
        web: yellowllapp-pods
        env: prod
        frontend: web
    spec: 
      containers:
        - name: yellowimage
          image:
          ports:
            - name: yellowapp-ports
              containerport: 80
              protocol: TCP
          startupprobe: 
            httpget:
              path: "/hemanth"
              port: 80
          livenessprobe:
            tcpSocket:
              port: 80
          readinessprobe:
            exec:
              command:
                - echo hi
          resources:
            requests:
              cpu: 100M
              memory: 200Mi
            limits:
              cpu: 300M
              memory: 300Mi
           



    